/*
 * 微米云服务接口全集
 * The wemiyun  services
 *
 * OpenAPI spec version: 1.2.20170327
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
